default_context:
  project_name: '{{ fastapi_cookie_cutter.project_name }}'
  project_slug: '{{ fastapi_cookie_cutter.project_slug }}'
  domain_main: '{{ fastapi_cookie_cutter.domain_main }}'
  domain_staging: '{{ fastapi_cookie_cutter.domain_staging }}'
  docker_swarm_stack_name_main: '{{ fastapi_cookie_cutter.docker_swarm_stack_name_main }}'
  docker_swarm_stack_name_staging: '{{ fastapi_cookie_cutter.docker_swarm_stack_name_staging }}'
  secret_key: '{{ fastapi_cookie_cutter.secret_key }}'
  first_superuser: '{{ fastapi_cookie_cutter.first_superuser }}'
  first_superuser_password: '{{ fastapi_cookie_cutter.first_superuser_password }}'
  backend_cors_origins: '{{ fastapi_cookie_cutter.backend_cors_origins }}'
  smtp_port: '{{ fastapi_cookie_cutter.smtp_port }}'
  smtp_host: '{{ fastapi_cookie_cutter.smtp_host }}'
  smtp_user: '{{ fastapi_cookie_cutter.smtp_user }}'
  smtp_password: '{{ fastapi_cookie_cutter.smtp_password }}'
  smtp_emails_from_email: '{{ fastapi_cookie_cutter.smtp_emails_from_email }}'
  postgres_password: '{{ fastapi_cookie_cutter.postgres_password }}'
  pgadmin_default_user: '{{ fastapi_cookie_cutter.pgadmin_default_user }}'
  pgadmin_default_user_password: '{{ fastapi_cookie_cutter.pgadmin_default_user_password }}'
  traefik_constraint_tag: '{{ fastapi_cookie_cutter.traefik_constraint_tag }}'
  traefik_constraint_tag_staging: '{{ fastapi_cookie_cutter.traefik_constraint_tag_staging }}'
  traefik_public_constraint_tag: '{{ fastapi_cookie_cutter.traefik_public_constraint_tag }}'
  flower_auth: '{{ fastapi_cookie_cutter.flower_auth }}'
  sentry_dsn: '{{ fastapi_cookie_cutter.sentry_dsn }}'
  docker_image_prefix: '{{ fastapi_cookie_cutter.docker_image_prefix }}'
  docker_image_backend: '{{ fastapi_cookie_cutter.docker_image_backend }}'
  docker_image_celeryworker: '{{ fastapi_cookie_cutter.docker_image_celeryworker }}'
  docker_image_frontend: '{{ fastapi_cookie_cutter.docker_image_frontend }}'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
