name: PR Title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: Setup Python
          uses: actions/setup-python@v2
          with:
              python-version: 3.9

        - name: Install Poetry
          uses: snok/install-poetry@v1
          with:
            virtualenvs-path: ~/.virtualenvs

        - name: Cache Poetry virtualenv
          uses: actions/cache@v2
          id: cache
          with:
            path: ~/.virtualenvs
            key: poetry-${{ hashFiles('**/poetry.lock') }}
            restore-keys: |
              poetry-${{ hashFiles('**/poetry.lock') }}

        - name: Set Poetry config
          run: |
            poetry config virtualenvs.in-project false
            poetry config virtualenvs.path ~/.virtualenvs

        - name: Install Dependencies
          run: |
            cd fastapi_cookie_cutter
            cd backend
            cd app
            poetry install
          if: steps.cache.outputs.cache-hit != 'true'

        - name: Check PR Title
          env:
              TITLE: ${{ github.event.pull_request.title }}
          run: cz check --message "$TITLE"
